name: Compass Icons CI

on:
    workflow_dispatch:
    repository_dispatch:
    push:
        paths:
            - 'packages/compass-icons/*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: npm install and package
              working-directory: ./packages/compass-icons
              run: |
                  npm install
                  npm run build
            - name: Copy config file to build folder
              working-directory: ./packages/compass-icons
              run: cp config.json ./build
            - name: Archive artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: Build folder
                  path: packages/compass-icons/build
