name: Compass Icons CI

on:
    workflow_dispatch:
    push:
        branches:
            - master
        paths:
            - 'packages/compass-icons/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: npm install and package
              working-directory: ./packages/compass-icons
              run: |
                  npm install
                  npm run package
            - name: Rename downloaded fontello package
              working-directory: ./packages/compass-icons
              run: mv fontello* fontello
            - name: Archive artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: CompassIconFont
                  path: packages/compass-icons/fontello
